{{- $fullName := include "deploy.fullname" . -}}
{{- range $stage, $deployment := index .Values "deployments" }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $fullName }}-{{ $stage }}
  labels:
    helm.sh/chart: {{ include "deploy.chart" $ }}
    app.kubernetes.io/instance: {{ $.Release.Name }}
    app.kubernetes.io/managed-by: {{ $.Release.Service }}
    app.kubernetes.io/name: {{ include "deploy.name" $ }}
    app.kubernetes.io/stage: {{ $stage }}
    app: {{ include "deploy.name" $ }}
    tags.datadoghq.com/service: {{ $fullName }}
    tags.datadoghq.com/env: {{ $stage }}
    tags.datadoghq.com/version: {{ $deployment.version }}
    flow.io/version: {{ $deployment.version }}
    flow.io/team: {{ $.Values.team }}
spec:
  {{- if or (ne $.Values.rollout.enabled true) (eq $.Values.rollout.migration true) }}
  replicas: {{ $deployment.minReplicas }}
  {{ else }}
  replicas: 0
  {{- end }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "deploy.name" $ }}
      app.kubernetes.io/instance: {{ $.Release.Name }}
      app.kubernetes.io/stage: {{ $stage }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "deploy.name" $ }}
        app.kubernetes.io/instance: {{ $.Release.Name }}
        app.kubernetes.io/stage: {{ $stage }}
        app: {{ include "deploy.name" $ }}
        tags.datadoghq.com/service: {{ $fullName }}
        tags.datadoghq.com/env: {{ $stage }}
        tags.datadoghq.com/version: {{ $deployment.version }}
        flow.io/version: {{ $deployment.version }}
        flow.io/team: {{ $.Values.team }}
      annotations:
        {{- if $.Values.iamRole }}
        iam.amazonaws.com/role: {{ $.Values.iamRole }}
        {{- end }}
        {{- if $deployment.disableAutoscalerEviction }}
        cluster-autoscaler.kubernetes.io/safe-to-evict: "false"
        {{- end }}
        sumologic.com/sourceCategory: {{ $fullName }}
        sidecar.istio.io/logLevel: {{ $.Values.istio.logLevel }}
        {{- if $.Values.istio.agentLogEnabled }}
        sidecar.istio.io/agentLogLevel: {{ $.Values.istio.agentLogLevel }}
        {{- end }}
        proxy.istio.io/config: '{"terminationDrainDuration": {{ $.Values.istio.terminationDrainDuration }}}'
    spec:
      terminationGracePeriodSeconds: {{ default "60" $deployment.terminationGracePeriodSeconds }}
      containers:
        - name: {{ $fullName }}
          image: "{{ $.Values.image.repository }}:{{ $deployment.version }}"
          imagePullPolicy: {{ $.Values.image.pullPolicy }}
          env:
            {{- if $.Values.jvmOpts.enabled }}
            - name: JAVA_OPTS
              {{- with $.Values.jvmOpts }}
              value: "-Xms{{ .memory }} -Xmx{{ .memory }} {{ .extraArgs}}"
              {{- end}}
            {{- end }}
            - name: FLOW_KUBERNETES_NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: FLOW_KUBERNETES_NODE_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.hostIP
            - name: FLOW_KUBERNETES_POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: FLOW_KUBERNETES_POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: FLOW_KUBERNETES_POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: FLOW_KUBERNETES_POD_UID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.uid
            - name: DD_SERVICE
              value: {{ $fullName }}
            - name: DD_ENV
              value: {{ $stage }}
            - name: DD_VERSION
              value: {{ $deployment.version }}
            - name: DD_JMXFETCH_STATSD_HOST
              value: 'unix:///var/run/datadog/dsd.socket'
            - name: DD_DOGSTATSD_URL
              value: 'unix:///var/run/datadog/dsd.socket'
            - name: DD_TRACE_AGENT_URL
              value: 'unix:///var/run/datadog/apm.socket'
            - name: DD_SERVICE_MAPPING
              value: "postgresql:{{ $fullName }}-postgresql,java-aws-sdk:{{ $fullName }}-aws-sdk"
            - name: DD_TAGS
              value: "team:{{ $.Values.team }}"
            - name: DD_KUBERNETES_POD_LABELS_AS_TAGS
              value: '{"*": "label_%%label%%"}'
            - name: DD_CONTAINER_ENV_AS_TAGS
              value: '{"FLOW_KUBERNETES_POD_NAME":"env_flow_kubernetes_pod_name","FLOW_KUBERNETES_POD_NAMESPACE":"env_flow_kubernetes_pod_namespace"}'
            {{- if $deployment.env }}
{{ toYaml $deployment.env | indent 12 }}
            {{- end }}
          {{- if $.Values.image.args }}
          args: {{ list ($.Values.image.args | quote) }}
          {{- end }}
          ports:
            - name: http
              containerPort: {{ $.Values.service.port }}
              protocol: TCP
            {{- if $.Values.service.httpsPort }}
            - name: https
              containerPort: {{ $.Values.service.httpsPort }}
              protocol: TCP
            {{- end }}
          {{- if $deployment.containerSecurityContext }}
          securityContext: {{- toYaml $deployment.containerSecurityContext | nindent 12 }}
          {{- end }}
          {{- if $deployment.preStophookEnabled }}
          lifecycle:
            preStop:
              exec:
                command: ["/bin/sh", "-c", "sleep 5"]
          {{- end }}
          volumeMounts:
            - name: dsdsocket
              mountPath: /var/run/datadog
            - name: heap-dumps
              mountPath: /dumps
          startupProbe:
            httpGet:
              path: {{ default (default "/_internal_/healthcheck" $.Values.service.healthcheckEndpoint) $.Values.service.startupHealthcheckEndpoint }}
              port: http
            failureThreshold: 30
            periodSeconds: 10
          {{- if $deployment.livenessProbeEnabled }}
          livenessProbe:
            httpGet:
              path: {{ default (default "/_internal_/healthcheck" $.Values.service.healthcheckEndpoint) $.Values.service.livenessHealthcheckEndpoint }}
              port: http
            failureThreshold: 6
            periodSeconds: 10
            timeoutSeconds: 5
          {{- end }}
          readinessProbe:
            httpGet:
              path: {{ default (default "/_internal_/healthcheck" $.Values.service.healthcheckEndpoint) $.Values.service.readinessHealthcheckEndpoint }}
              port: http
            failureThreshold: 1
            periodSeconds: 10
            timeoutSeconds: 1
          resources:
{{ toYaml $.Values.resources | indent 12 }}
    {{- with $.Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with $.Values.imagePullSecrets }}
      imagePullSecrets:
{{ toYaml . | indent 8 }}
    {{- end }}
      {{- if $deployment.globalSecurityContext }}
      securityContext: {{- toYaml $deployment.globalSecurityContext | nindent 8 }}
      {{- end }}
      {{- if $.Values.affinity.enabled }}
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - {{ include "deploy.name" $ }}
              topologyKey: topology.kubernetes.io/zone
      {{- end }}
      {{- if $.Values.topologySpreadConstraints.enabled }}
      topologySpreadConstraints:
        - maxSkew: 1
          topologyKey: topology.kubernetes.io/zone
          whenUnsatisfiable: ScheduleAnyway
          labelSelector:
            matchLabels:
              app: {{ include "deploy.name" $ }}
      {{- end }}
      {{- if $deployment.sysctlEnabled }}
      initContainers:
      - name: tunables
        image: busybox:1.34.1
        imagePullPolicy: IfNotPresent
        securityContext:
          privileged: true
        command: [ 'sh', '-c', 'sysctl -w  net.ipv4.tcp_tw_reuse=1 && sysctl -w net.ipv4.tcp_slow_start_after_idle=0 && sysctl -w net.ipv4.tcp_max_syn_backlog=4096' ]
      {{- end }}
    {{- with $.Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
      dnsConfig:
        options:
          - name: ndots
            value: "1"
      volumes:
        - name: dsdsocket
          hostPath:
            path: /var/run/datadog/
            type: DirectoryOrCreate
        - name: heap-dumps
          emptyDir: {}
      {{- if $deployment.serviceAccountName }}
      serviceAccountName: {{ $deployment.serviceAccountName }}
      {{- end }}
  strategy:
    type: {{ $deployment.strategy | default "RollingUpdate" }}
---
{{- end -}}
