{{- $fullName := include "deploy.fullname" . -}}
{{- if and ($.Values.istioIngress.enabled) (kindIs "invalid" $.Values.istioIngress.gateways) (not $.Values.service.httpsPort) -}}
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: {{ default $fullName $.Values.service.nameOverride }}-flow-io
  labels:
    app.kubernetes.io/name: {{ include "deploy.name" $ }}
    helm.sh/chart: {{ include "deploy.chart" $ }}
    app.kubernetes.io/instance: {{ $.Release.Name }}
    app.kubernetes.io/managed-by: {{ $.Release.Service }}
    app: {{ include "deploy.name" $ }}
  annotations:
    kubernetes.io/ingress.class: "ingressgateway"
    kubernetes.io/ingress.tld: "api.flow.io"
    {{- if $.Values.istioIngress.defaultCFProxy }}
    external-dns.alpha.kubernetes.io/cloudflare-proxied: "true"
    {{ else }}
    external-dns.alpha.kubernetes.io/ttl: "120"
    {{- end }}
    {{- if $.Values.istio.alb }}
    external-dns.alpha.kubernetes.io/target: "{{ default "alb-prod.api.flow.io"  $.Values.istio.albApiTarget }}"
    external-dns.alpha.kubernetes.io/alias: "true"
    {{- end }}

spec:
  selector:
    istio: ingressgateway
  servers:
    - port:
        number: 80
        name: http
        protocol: HTTP2
      hosts:
        - {{ default $fullName $.Values.service.nameOverride }}.api.flow.io
      tls:
        httpsRedirect: true
    - port:
        number: 443
        name: https
        protocol: HTTP2
      hosts:
        - {{ default $fullName $.Values.service.nameOverride }}.api.flow.io
---
{{- end }}
