{{- if or (ne $.Values.rollout.enabled true) (eq $.Values.rollout.migration true) }}
{{- $fullName := include "deploy.fullname" . -}}
{{- range $key, $service := index .Values "istioService" }}
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: {{ $fullName }}-{{ $key }}
spec:
  host: {{ default $fullName $.Values.service.nameOverride }}
  trafficPolicy:
    {{- if and ($service.idleTimeoutOverride) (not $.Values.service.httpsPort) }}
    connectionPool:
      http:
        idleTimeout: {{ default "70s" $service.idleTimeoutValue }}
    {{- end }}
    tls:
    {{- if $.Values.service.httpsPort }}
      mode: SIMPLE
    {{ else }}
      mode: ISTIO_MUTUAL
    {{- end }}
    loadBalancer:
      simple: {{ default "LEAST_CONN" $service.lbAlgorithm }}
  subsets:
{{- range $stage := $service.stages }}
    - name: {{ $stage.deployment }}
      labels:
        app.kubernetes.io/stage: {{ $stage.deployment }}
{{- end }}

---

apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ $fullName }}-{{ $key }}
  labels:
    app.kubernetes.io/name: {{ include "deploy.name" $ }}
    helm.sh/chart: {{ include "deploy.chart" $ }}
    app.kubernetes.io/instance: {{ $.Release.Name }}
    app.kubernetes.io/managed-by: {{ $.Release.Service }}
    app: {{ include "deploy.name" $ }}
spec:
  hosts:
{{- if kindIs "invalid" $service.hosts }}
    - {{ default $fullName $.Values.service.nameOverride }}
    - {{ default $fullName $.Values.service.nameOverride }}.api.flow.io
{{- else }}
{{ toYaml $service.hosts | indent 4 }}
{{- end }}
  gateways:
{{- if kindIs "invalid" $service.gateways }}
    - mesh
    - {{ default $fullName $.Values.service.nameOverride }}-flow-io
{{- else }}
{{ toYaml $service.gateways | indent 4 }}
{{- end }}
{{- if $.Values.service.httpsPort }}
  tls:
  - match:
    - port: 443
      sniHosts:
      - "*"
    route:
{{- range $stage := $service.stages }}
    - destination:
        host: {{ default $fullName $.Values.service.nameOverride }}
        port:
          number: 443
        subset:  {{ $stage.deployment }}
{{- end }}
{{ else }}
  http:
  - route:
{{- range $stage := $service.stages }}
    - destination:
        host: {{ default $fullName $.Values.service.nameOverride }}
        port:
          number: 80
        subset:  {{ $stage.deployment }}
{{- end }}
{{- end }}
    {{- if $.Values.istio.retries.enabled }}
    retries:
      attempts: {{ $.Values.istio.retries.attempts }}
      perTryTimeout: {{ $.Values.istio.retries.perTryTimeout }}
      retryOn: connect-failure,refused-stream,503
    {{- end }}
---
{{- end }}
{{- end }}
